// SIC Code to Industry Name mapping
// Source: SEC Standard Industrial Classification

export const SIC_CODES: Record<string, string> = {
	// Mining
	'1000': 'Metal Mining',
	'1040': 'Gold & Silver Ores',
	'1311': 'Crude Petroleum & Natural Gas',
	'1381': 'Drilling Oil & Gas Wells',
	'1382': 'Oil & Gas Field Exploration',
	'1389': 'Oil & Gas Field Services',

	// Construction
	'1500': 'Building Construction',
	'1520': 'Residential Building',
	'1531': 'Operative Builders',
	'1600': 'Heavy Construction',
	'1700': 'Construction Special Trade',

	// Manufacturing - Food
	'2000': 'Food & Kindred Products',
	'2011': 'Meat Packing Plants',
	'2013': 'Sausages & Prepared Meats',
	'2015': 'Poultry Processing',
	'2020': 'Dairy Products',
	'2030': 'Preserved Fruits & Vegetables',
	'2050': 'Bakery Products',
	'2080': 'Beverages',
	'2082': 'Malt Beverages',
	'2086': 'Bottled & Canned Soft Drinks',

	// Manufacturing - Textiles & Apparel
	'2200': 'Textile Mill Products',
	'2300': 'Apparel & Other Textile',
	'2320': "Men's & Boys' Furnishings",
	'2330': "Women's & Misses' Outerwear",
	'2340': "Women's & Children's Undergarments",

	// Manufacturing - Lumber & Paper
	'2400': 'Lumber & Wood Products',
	'2421': 'Sawmills & Planing Mills',
	'2451': 'Mobile Homes',
	'2500': 'Furniture & Fixtures',
	'2510': 'Household Furniture',
	'2600': 'Paper & Allied Products',
	'2621': 'Paper Mills',
	'2631': 'Paperboard Mills',
	'2670': 'Converted Paper & Paperboard',
	'2673': 'Plastics, Foil & Coated Paper Bags',

	// Manufacturing - Chemicals
	'2800': 'Chemicals & Allied Products',
	'2810': 'Industrial Inorganic Chemicals',
	'2820': 'Plastics & Synthetic Resins',
	'2821': 'Plastics Materials & Resins',
	'2833': 'Medicinal Chemicals & Botanicals',
	'2834': 'Pharmaceutical Preparations',
	'2835': 'In Vitro & In Vivo Diagnostics',
	'2836': 'Biological Products',
	'2840': 'Soap, Detergents & Cleaning',
	'2842': 'Specialty Cleaning & Polishing',
	'2844': 'Perfumes & Cosmetics',
	'2851': 'Paints & Allied Products',
	'2860': 'Industrial Organic Chemicals',
	'2870': 'Agricultural Chemicals',
	'2890': 'Miscellaneous Chemical Products',
	'2891': 'Adhesives & Sealants',

	// Manufacturing - Petroleum & Rubber
	'2911': 'Petroleum Refining',
	'3000': 'Rubber & Plastic Products',
	'3011': 'Tires & Inner Tubes',
	'3050': 'Gaskets & Rubber Hose',
	'3060': 'Fabricated Rubber Products',
	'3080': 'Miscellaneous Plastics',
	'3086': 'Plastics Foam Products',
	'3089': 'Plastics Products, NEC',

	// Manufacturing - Stone, Clay, Glass
	'3200': 'Stone, Clay, Glass & Concrete',
	'3211': 'Flat Glass',
	'3220': 'Glass & Glassware',
	'3221': 'Glass Containers',
	'3231': 'Glass Products from Purchased Glass',
	'3241': 'Cement, Hydraulic',
	'3270': 'Concrete, Gypsum & Plaster',

	// Manufacturing - Primary Metals
	'3300': 'Primary Metal Industries',
	'3310': 'Steel Works & Blast Furnaces',
	'3312': 'Steel Works & Blast Furnaces',
	'3317': 'Steel Pipe & Tubes',
	'3320': 'Iron & Steel Foundries',
	'3330': 'Primary Smelting & Refining',
	'3334': 'Primary Aluminum',
	'3350': 'Rolling, Drawing & Extruding',
	'3357': 'Nonferrous Wire Drawing',

	// Manufacturing - Fabricated Metal
	'3400': 'Fabricated Metal Products',
	'3411': 'Metal Cans',
	'3420': 'Cutlery, Handtools & Hardware',
	'3430': 'Heating Equipment & Plumbing',
	'3440': 'Fabricated Structural Metal',
	'3442': 'Metal Doors & Windows',
	'3443': 'Fabricated Plate Work',
	'3444': 'Sheet Metal Work',
	'3460': 'Metal Forgings & Stampings',
	'3469': 'Metal Stampings, NEC',
	'3470': 'Coating & Engraving',
	'3480': 'Ordnance & Accessories',
	'3490': 'Miscellaneous Fabricated Metal',

	// Manufacturing - Industrial Machinery
	'3500': 'Industrial Machinery & Equipment',
	'3510': 'Engines & Turbines',
	'3523': 'Farm Machinery & Equipment',
	'3524': 'Lawn & Garden Equipment',
	'3530': 'Construction & Mining Machinery',
	'3531': 'Construction Machinery',
	'3532': 'Mining Machinery',
	'3533': 'Oil & Gas Field Machinery',
	'3537': 'Industrial Trucks & Tractors',
	'3540': 'Metalworking Machinery',
	'3541': 'Machine Tools, Metal Cutting',
	'3550': 'Special Industry Machinery',
	'3555': 'Printing Trades Machinery',
	'3559': 'Special Industry Machinery, NEC',
	'3560': 'General Industrial Machinery',
	'3561': 'Pumps & Pumping Equipment',
	'3562': 'Ball & Roller Bearings',
	'3564': 'Industrial Fans & Blowers',
	'3567': 'Industrial Process Furnaces',
	'3569': 'General Industrial Machinery, NEC',
	'3570': 'Computer & Office Equipment',
	'3571': 'Electronic Computers',
	'3572': 'Computer Storage Devices',
	'3575': 'Computer Terminals',
	'3576': 'Computer Communication Equipment',
	'3577': 'Computer Peripheral Equipment',
	'3578': 'Calculating & Office Machines',
	'3579': 'Office Machines, NEC',
	'3580': 'Refrigeration & Service Machinery',
	'3585': 'Refrigeration & Heating Equipment',
	'3590': 'Miscellaneous Industrial Machinery',

	// Manufacturing - Electronic Equipment
	'3600': 'Electronic & Electrical Equipment',
	'3612': 'Power, Distribution & Transformers',
	'3613': 'Switchgear & Switchboard',
	'3620': 'Electrical Industrial Apparatus',
	'3621': 'Motors & Generators',
	'3630': 'Household Appliances',
	'3634': 'Electric Housewares & Fans',
	'3640': 'Electric Lighting & Wiring',
	'3651': 'Household Audio & Video',
	'3652': 'Phonograph Records & Tapes',
	'3661': 'Telephone & Telegraph Apparatus',
	'3663': 'Radio & TV Broadcasting Equipment',
	'3669': 'Communications Equipment, NEC',
	'3670': 'Electronic Components',
	'3672': 'Printed Circuit Boards',
	'3674': 'Semiconductors & Related Devices',
	'3677': 'Electronic Coils & Transformers',
	'3678': 'Electronic Connectors',
	'3679': 'Electronic Components, NEC',
	'3690': 'Miscellaneous Electrical Machinery',
	'3695': 'Magnetic & Optical Recording Media',

	// Manufacturing - Transportation Equipment
	'3700': 'Transportation Equipment',
	'3711': 'Motor Vehicles & Car Bodies',
	'3713': 'Truck & Bus Bodies',
	'3714': 'Motor Vehicle Parts',
	'3715': 'Truck Trailers',
	'3716': 'Motor Homes',
	'3720': 'Aircraft & Parts',
	'3721': 'Aircraft',
	'3724': 'Aircraft Engines & Parts',
	'3728': 'Aircraft Parts & Auxiliary',
	'3730': 'Ship & Boat Building',
	'3743': 'Railroad Equipment',
	'3751': 'Motorcycles, Bicycles & Parts',
	'3760': 'Guided Missiles & Space Vehicles',
	'3790': 'Miscellaneous Transportation',

	// Manufacturing - Measuring & Scientific Instruments
	'3800': 'Measuring & Analyzing Instruments',
	'3812': 'Search, Detection & Navigation',
	'3821': 'Laboratory Apparatus & Furniture',
	'3822': 'Automatic Environmental Controls',
	'3823': 'Industrial Instruments',
	'3824': 'Fluid Meters & Counting Devices',
	'3825': 'Instruments for Measuring',
	'3826': 'Laboratory Analytical Instruments',
	'3827': 'Optical Instruments & Lenses',
	'3829': 'Measuring & Controlling Devices',
	'3841': 'Surgical & Medical Instruments',
	'3842': 'Orthopedic & Prosthetic Appliances',
	'3843': 'Dental Equipment & Supplies',
	'3844': 'X-Ray Apparatus & Tubes',
	'3845': 'Electromedical & Electrotherapeutic',
	'3851': 'Ophthalmic Goods',
	'3861': 'Photographic Equipment & Supplies',
	'3873': 'Watches, Clocks & Parts',

	// Manufacturing - Miscellaneous
	'3900': 'Miscellaneous Manufacturing',
	'3910': 'Jewelry, Silverware & Plated Ware',
	'3911': 'Jewelry, Precious Metal',
	'3931': 'Musical Instruments',
	'3942': 'Dolls & Stuffed Toys',
	'3944': 'Games, Toys & Children Vehicles',
	'3949': 'Sporting & Athletic Goods, NEC',
	'3950': 'Pens, Pencils & Office Supplies',
	'3960': 'Costume Jewelry & Novelties',
	'3990': 'Miscellaneous Manufacturing, NEC',

	// Transportation
	'4000': 'Railroad Transportation',
	'4011': 'Railroads, Line-Haul',
	'4100': 'Local & Suburban Transit',
	'4210': 'Trucking & Courier Services',
	'4213': 'Trucking, Except Local',
	'4220': 'Public Warehousing & Storage',
	'4231': 'Terminal & Joint Terminal',
	'4400': 'Water Transportation',
	'4412': 'Deep Sea Foreign Transport',
	'4481': 'Deep Sea Passenger Transport',
	'4500': 'Transportation by Air',
	'4512': 'Air Transportation, Scheduled',
	'4513': 'Air Courier Services',
	'4522': 'Air Transportation, Nonscheduled',
	'4581': 'Airports, Flying Fields & Services',
	'4600': 'Pipelines, Except Natural Gas',
	'4610': 'Pipelines, Crude Petroleum',
	'4700': 'Transportation Services',
	'4731': 'Arrangement of Freight',
	'4812': 'Radiotelephone Communications',
	'4813': 'Telephone Communications',
	'4822': 'Telegraph & Other Message',
	'4832': 'Radio Broadcasting',
	'4833': 'Television Broadcasting',
	'4841': 'Cable & Other Pay Television',
	'4899': 'Communications Services, NEC',

	// Utilities
	'4900': 'Electric, Gas & Sanitary Services',
	'4911': 'Electric Services',
	'4922': 'Natural Gas Transmission',
	'4923': 'Natural Gas Transmission & Distribution',
	'4924': 'Natural Gas Distribution',
	'4931': 'Electric & Other Services Combined',
	'4932': 'Gas & Other Services Combined',
	'4941': 'Water Supply',
	'4950': 'Sanitary Services',
	'4953': 'Refuse Systems',
	'4955': 'Hazardous Waste Management',
	'4991': 'Cogeneration & Small Power',

	// Wholesale Trade
	'5000': 'Wholesale Trade - Durable Goods',
	'5010': 'Motor Vehicles & Automotive Parts',
	'5013': 'Motor Vehicle Supplies & Parts',
	'5020': 'Furniture & Home Furnishings',
	'5030': 'Lumber & Other Construction',
	'5040': 'Professional & Commercial Equipment',
	'5045': 'Computers & Computer Peripheral',
	'5047': 'Medical, Dental & Hospital',
	'5050': 'Metals & Minerals, Except Petroleum',
	'5051': 'Metals Service Centers & Offices',
	'5060': 'Electrical Goods',
	'5063': 'Electrical Apparatus & Equipment',
	'5064': 'Electrical Appliances, TV & Radio',
	'5065': 'Electronic Parts & Equipment',
	'5070': 'Hardware, Plumbing & Heating',
	'5072': 'Hardware',
	'5080': 'Machinery, Equipment & Supplies',
	'5082': 'Construction & Mining Machinery',
	'5084': 'Industrial Machinery & Equipment',
	'5090': 'Miscellaneous Durable Goods',
	'5094': 'Jewelry, Watches & Precious Stones',
	'5099': 'Durable Goods, NEC',
	'5100': 'Wholesale Trade - Nondurable Goods',
	'5110': 'Paper & Paper Products',
	'5122': 'Drugs, Drug Proprietaries & Sundries',
	'5130': 'Apparel, Piece Goods & Notions',
	'5140': 'Groceries & Related Products',
	'5141': 'Groceries, General Line',
	'5150': 'Farm Product Raw Materials',
	'5160': 'Chemicals & Allied Products',
	'5171': 'Petroleum Bulk Stations & Terminals',
	'5172': 'Petroleum & Petroleum Products',
	'5180': 'Beer, Wine & Distilled Alcoholic',
	'5190': 'Miscellaneous Nondurable Goods',
	'5199': 'Nondurable Goods, NEC',

	// Retail Trade
	'5200': 'Building Materials & Hardware',
	'5211': 'Lumber & Building Materials',
	'5271': 'Mobile Home Dealers',
	'5300': 'General Merchandise Stores',
	'5311': 'Department Stores',
	'5331': 'Variety Stores',
	'5399': 'Miscellaneous General Merchandise',
	'5400': 'Food Stores',
	'5411': 'Grocery Stores',
	'5412': 'Convenience Stores',
	'5500': 'Auto Dealers & Gas Stations',
	'5531': 'Auto & Home Supply Stores',
	'5600': 'Apparel & Accessory Stores',
	'5621': "Women's Clothing Stores",
	'5651': 'Family Clothing Stores',
	'5661': 'Shoe Stores',
	'5700': 'Home Furniture & Equipment',
	'5712': 'Furniture Stores',
	'5731': 'Radio, TV & Consumer Electronics',
	'5734': 'Computer & Computer Software',
	'5735': 'Record & Prerecorded Tape',
	'5812': 'Eating Places',
	'5900': 'Miscellaneous Retail',
	'5912': 'Drug Stores & Proprietary',
	'5940': 'Miscellaneous Shopping Goods',
	'5941': 'Sporting Goods & Bicycle Shops',
	'5942': 'Book Stores',
	'5944': 'Jewelry Stores',
	'5945': 'Hobby, Toy & Game Shops',
	'5960': 'Nonstore Retailers',
	'5961': 'Catalog & Mail-Order Houses',
	'5990': 'Retail Stores, NEC',

	// Finance
	'6000': 'Depository Institutions',
	'6020': 'Commercial Banks',
	'6021': 'National Commercial Banks',
	'6022': 'State Commercial Banks',
	'6029': 'Commercial Banks, NEC',
	'6035': 'Savings Institutions, Federally',
	'6036': 'Savings Institutions, Not Federally',
	'6099': 'Functions Related to Depository',
	'6111': 'Federal & Federally-Sponsored Credit',
	'6120': 'Savings & Loan Associations',
	'6140': 'Personal Credit Institutions',
	'6141': 'Personal Credit Institutions',
	'6150': 'Business Credit Institutions',
	'6153': 'Short-Term Business Credit',
	'6159': 'Miscellaneous Business Credit',
	'6162': 'Mortgage Bankers & Loan',
	'6163': 'Loan Brokers',
	'6172': 'Finance Lessors',
	'6189': 'Asset-Backed Securities',
	'6199': 'Finance Services',
	'6200': 'Security & Commodity Brokers',
	'6211': 'Security Brokers & Dealers',
	'6221': 'Commodity Contracts Dealers',
	'6282': 'Investment Advice',
	'6311': 'Life Insurance',
	'6321': 'Accident & Health Insurance',
	'6324': 'Hospital & Medical Service Plans',
	'6331': 'Fire, Marine & Casualty Insurance',
	'6351': 'Surety Insurance',
	'6361': 'Title Insurance',
	'6399': 'Insurance Carriers, NEC',
	'6411': 'Insurance Agents, Brokers',
	'6500': 'Real Estate',
	'6510': 'Real Estate Operators & Lessors',
	'6512': 'Operators of Nonresidential Buildings',
	'6519': 'Lessors of Real Property, NEC',
	'6531': 'Real Estate Agents & Managers',
	'6532': 'Real Estate Dealers',
	'6552': 'Land Subdividers & Developers',
	'6770': 'Blank Checks',
	'6792': 'Oil Royalty Traders',
	'6794': 'Patent Owners & Lessors',
	'6795': 'Mineral Royalty Traders',
	'6798': 'Real Estate Investment Trusts',
	'6799': 'Investors, NEC',

	// Services
	'7000': 'Hotels, Rooming Houses & Camps',
	'7011': 'Hotels & Motels',
	'7200': 'Personal Services',
	'7310': 'Advertising Services',
	'7311': 'Advertising Agencies',
	'7320': 'Consumer Credit Reporting',
	'7330': 'Mailing, Reproduction & Commercial Art',
	'7331': 'Direct Mail Advertising',
	'7340': 'Services to Dwellings & Buildings',
	'7350': 'Miscellaneous Equipment Rental',
	'7359': 'Equipment Rental & Leasing, NEC',
	'7361': 'Employment Agencies',
	'7363': 'Help Supply Services',
	'7370': 'Computer Programming & Data Processing',
	'7371': 'Computer Programming Services',
	'7372': 'Prepackaged Software',
	'7373': 'Computer Integrated Systems Design',
	'7374': 'Computer Processing & Data Preparation',
	'7375': 'Information Retrieval Services',
	'7377': 'Computer Rental & Leasing',
	'7378': 'Computer Maintenance & Repair',
	'7379': 'Computer Related Services, NEC',
	'7380': 'Miscellaneous Business Services',
	'7381': 'Detective, Guard & Armored Car',
	'7384': 'Photofinishing Laboratories',
	'7385': 'Telephone Interconnect Systems',
	'7389': 'Business Services, NEC',
	'7500': 'Automotive Repair, Services & Parking',
	'7510': 'Automotive Rental & Leasing',
	'7600': 'Miscellaneous Repair Services',
	'7812': 'Motion Picture & Video Production',
	'7819': 'Services Allied to Motion Picture',
	'7822': 'Motion Picture & Video Distribution',
	'7829': 'Services Allied to Motion Picture Distribution',
	'7830': 'Motion Picture Theaters',
	'7841': 'Video Tape Rental',
	'7900': 'Amusement & Recreation Services',
	'7948': 'Racing, Including Track Operation',
	'7990': 'Miscellaneous Amusement & Recreation',
	'7997': 'Membership Sports & Recreation',
	'8000': 'Health Services',
	'8011': 'Offices & Clinics of Doctors',
	'8050': 'Nursing & Personal Care Facilities',
	'8051': 'Skilled Nursing Care Facilities',
	'8060': 'Hospitals',
	'8062': 'General Medical & Surgical Hospitals',
	'8071': 'Medical Laboratories',
	'8082': 'Home Health Care Services',
	'8090': 'Miscellaneous Health & Allied Services',
	'8093': 'Specialty Outpatient Facilities',
	'8111': 'Legal Services',
	'8200': 'Educational Services',
	'8300': 'Social Services',
	'8351': 'Child Day Care Services',
	'8700': 'Engineering, Accounting & Research',
	'8711': 'Engineering Services',
	'8721': 'Accounting, Auditing & Bookkeeping',
	'8731': 'Commercial Physical & Biological Research',
	'8732': 'Commercial Economic, Sociological Research',
	'8733': 'Noncommercial Research Organizations',
	'8734': 'Testing Laboratories',
	'8741': 'Management Services',
	'8742': 'Management Consulting Services',
	'8744': 'Facilities Support Management',
	'8748': 'Business Consulting Services, NEC',
	'8880': 'American Depositary Receipts',
	'8888': 'Foreign Governments',
	'8900': 'Miscellaneous Services',
	'9995': 'Non-Operating Establishments'
};

/**
 * Get industry name for a SIC code
 */
export function getIndustryName(sicCode: string | number): string {
	const code = String(sicCode);
	if (SIC_CODES[code]) {
		return SIC_CODES[code];
	}

	// Try to find a parent category (first 2 digits)
	const prefix2 = code.slice(0, 2) + '00';
	if (SIC_CODES[prefix2]) {
		return SIC_CODES[prefix2];
	}

	// Try to find a parent category (first 3 digits)
	const prefix3 = code.slice(0, 3) + '0';
	if (SIC_CODES[prefix3]) {
		return SIC_CODES[prefix3];
	}

	return 'Other Industry';
}

/**
 * Get sector category for a SIC code
 */
export function getSectorCategory(sicCode: string | number): string {
	const code = Number(sicCode);

	if (code < 1000) return 'Agriculture';
	if (code < 1500) return 'Mining';
	if (code < 1800) return 'Construction';
	if (code < 4000) return 'Manufacturing';
	if (code < 5000) return 'Transportation & Utilities';
	if (code < 5200) return 'Wholesale Trade';
	if (code < 6000) return 'Retail Trade';
	if (code < 7000) return 'Finance & Insurance';
	if (code < 9000) return 'Services';
	return 'Public Administration';
}
